exports.bookNames = ["Genesis","Exodus","Leviticus","Numbers","Deuteronomy","Joshua","Judges","Ruth","1 Samuel","2 Samuel","1 Kings","2 Kings","1 Chronicles","2 Chronicles","Ezra","Nehemiah","Esther","Job","Psalms","Proverbs","Ecclesiastes","Song of Solomon","Isaiah","Jeremiah","Lamentations","Ezekiel","Daniel","Hosea","Joel","Amos","Obadiah","Jonah","Micah","Nahum","Habakkuk","Zephaniah","Haggai","Zechariah","Malachi","Matthew","Mark","Luke","John","Acts","Romans","1 Corinthians","2 Corinthians","Galatians","Ephesians","Philippians","Colossians","1 Thessalonians","2 Thessalonians","1 Timothy","2 Timothy","Titus","Philemon","Hebrews","James","1 Peter","2 Peter","1 John","2 John","3 John","Jude","Revelation"]

exports.bookNamesNormalized =
    'GEN': 'Genesis'
    'EXO': 'Exodus'
    'LEV': 'Leviticus'
    'NUM': 'Numbers'
    'DEU': 'Deuteronomy'
    'JOS': 'Joshua'
    'JDG': 'Judges'
    'RUT': 'Ruth'
    '1SA': '1 Samuel'
    '2SA': '2 Samuel'
    '1KI': '1 Kings'
    '2KI': '2 Kings'
    '1CH': '1 Chronicles'
    '2CH': '2 Chronicles'
    'EZR': 'Ezra'
    'NEH': 'Nehemiah'
    'EST': 'Esther'
    'JOB': 'Job'
    'PSA': 'Psalms'
    'PSALM': 'Psalms'
    'PRO': 'Proverbs'
    'ECC': 'Ecclesiastes'
    'SOS': 'Song of Solomon'
    'ISA': 'Isaiah'
    'JER': 'Jeremiah'
    'LAM': 'Lamentations'
    'EZE': 'Ezekiel'
    'DAN': 'Daniel'
    'HOS': 'Hosea'
    'JOE': 'Joel'
    'AMO': 'Amos'
    'OBA': 'Obadiah'
    'JON': 'Jonah'
    'MIC': 'Micah'
    'NAH': 'Nahum'
    'HAB': 'Habakkuk'
    'ZEP': 'Zephaniah'
    'HAG': 'Haggai'
    'ZEC': 'Zechariah'
    'MAL': 'Malachi'
    'MAT': 'Matthew'
    'MATT': 'Matthew'
    'MAR': 'Mark'
    'LUK': 'Luke'
    'JOH': 'John'
    'ACT': 'Acts'
    'ROM': 'Romans'
    '1CO': '1 Corinthians'
    '1 COR': '1 Corinthians'
    '2CO': '2 Corinthians'
    'GAL': 'Galatians'
    'EPH': 'Ephesians'
    'PHP': 'Philippians'
    'COL': 'Colossians'
    '1TH': '1 Thessalonians'
    '2TH': '2 Thessalonians'
    '1TI': '1 Timothy'
    '1TIM': '1 Timothy'
    '2TI': '2 Timothy'
    'TIT': 'Titus'
    'PHM': 'Philemon'
    'HEB': 'Hebrews'
    'JAM': 'James'
    'JAS': 'James'
    '1PE': '1 Peter'
    '2PE': '2 Peter'
    '1JO': '1 John'
    '2JO': '2 John'
    '3JO': '3 John'
    'JDE': 'Jude'
    'REV': 'Revelation'

# Normalize a Bible reference, changing the book name if needed
exports.bookNormalize = (ref) ->
    re = /(?:[1-9]\s*)?[a-z]+/i
    match = re.exec ref
    if match and exports.bookNamesNormalized[match[0].toUpperCase()]
        ref = ref.replace re, exports.bookNamesNormalized[match[0].toUpperCase()]

    return ref
